version: '3.8'

services:
  respzona-bot:
    build: .
    container_name: respzona-bot
    ports:
      - "5000:5000"
    environment:
      TOKEN: "8501298263:AAFsKnHjy9ha9pWji7j36kfQ3e5za01aYdQ"
      WEBHOOK_URL: "https://твой-домен.com/webhook"
      WEBHOOK_PORT: "5000"
    volumes:
      - ./users_data.json:/app/users_data.json
      - ./logs:/app/logs
    restart: always
    networks:
      - respzona-network

networks:
  respzona-network:
    driver: bridge
